
# OS
dist: trusty
sudo: required
cache:
    apt: true

# Git
branches:
    only:
        - master
git:
    depth: 10

# Language
language: php
php:
    - 5.4

install:
    - sudo pip install lxml

# Test
script:
    - python --version
    - python -c "import lxml"
    - python -c "import lxml.html"
