
# OS
dist: trusty
sudo: required
cache:
    apt: true

# Git
branches:
    only:
        - master
git:
    depth: 10

# Language
language: php
php:
    - 5.4

# Show python version
before_install:
    - python --version
    - pip install --upgrade pip

# Install dependencies
install:
    - pip install lxml

# Test
script:
    - python -c "import lxml"
    - python -c "import lxml.html"
