
# OS
dist: trusty
sudo: required
cache:
    apt: true

# Git
branches:
    only:
        - master
git:
    depth: 10

# Language
language: php
php:
    - 5.4

# Show python version
before_install:
    - python --version

# Install dependencies
install:
    - sudo pip install lxml

# Test
script:
    - python -c "import lxml"
